In [1]:
import os
os.chdir('/Users/alfredkim/study/mlinaction/Ch05')

In [2]:
import logRegres


In [26]:
reload(logRegres)
dataArr, labelMat = logRegres.loadDataSet()
print labelMat
logRegres.gradAscent(dataArr, labelMat)

[0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0]


matrix([[ 4.12414349],
        [ 0.48007329],
        [-0.6168482 ]])

In [32]:
a = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b = ones((3,1))
print mat(a)
print shape(a)
print mat(a)*b
h =  logRegres.sigmoid(mat(a)*b)
err = mat([1,1,0,0]).transpose()-h
print "---"
print h
print "---"
print mat(a).transpose()*err

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 6.]
 [15.]
 [24.]
 [33.]]
---
[[0.99752738]
 [0.99999969]
 [1.        ]
 [1.        ]]
---
[[-16.99752615]
 [-18.99505322]
 [-20.99258029]]
